[workspace.package]
edition = "2021"
authors = ["Nicholas Crothers <ncrothers523@gmail.com>"]
license = "MIT"
repository = "https://github.com/ncrothers/behaviortree-rs"

[workspace]
members = [
    "behaviortree-rs",
    "behaviortree-rs-derive",
]